name: deelze
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  dartz: ^0.10.1
  get_it: ^7.2.0
  dio: ^5.1.1
  go_router: ^10.1.2
  intl_phone_number_input: ^0.7.3+1
  flutter_verification_code: ^1.1.7
  pin_code_fields: ^8.0.1
  qr_code_scanner: ^1.0.1
  google_maps_flutter: ^2.5.0
  flutter_svg: ^2.0.7
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.1
  equatable: ^2.0.5
  cloud_firestore: ^4.9.3
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  logger: ^1.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-VariableFont_wght.ttf