// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUznj_rl8SYO9N_mcInUOlR2ueHx5z00w',
    appId: '1:592166478639:web:831094f38d60b2074a77da',
    messagingSenderId: '592166478639',
    projectId: 'deelze-b979a',
    authDomain: 'deelze-b979a.firebaseapp.com',
    storageBucket: 'deelze-b979a.appspot.com',
    measurementId: 'G-NTFGLWJ662',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA74ZHakINq-cGc9_621Ume2h2Yakz7DQk',
    appId: '1:592166478639:android:11186c9caa7759cb4a77da',
    messagingSenderId: '592166478639',
    projectId: 'deelze-b979a',
    storageBucket: 'deelze-b979a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjBZg_UaQo8rf-qIaGqPVKAU6CyJv_lBk',
    appId: '1:592166478639:ios:5dcd25c43d415c284a77da',
    messagingSenderId: '592166478639',
    projectId: 'deelze-b979a',
    storageBucket: 'deelze-b979a.appspot.com',
    iosBundleId: 'com.example.deelze',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjBZg_UaQo8rf-qIaGqPVKAU6CyJv_lBk',
    appId: '1:592166478639:ios:35fca11cd5c25d3e4a77da',
    messagingSenderId: '592166478639',
    projectId: 'deelze-b979a',
    storageBucket: 'deelze-b979a.appspot.com',
    iosBundleId: 'com.example.deelze.RunnerTests',
  );
}
