// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBfU6TKMSMcAa0KDGVvQvTPRQBw8yR71E',
    appId: '1:644074355722:web:404a2655b44bf0599fb3f3',
    messagingSenderId: '644074355722',
    projectId: 'posmission-dev',
    authDomain: 'posmission-dev.firebaseapp.com',
    storageBucket: 'posmission-dev.appspot.com',
    measurementId: 'G-BZH00RSMEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuRVPcRaQii2gb6JkHR77OYV6LPMKZ-Jg',
    appId: '1:644074355722:android:ee866101995549519fb3f3',
    messagingSenderId: '644074355722',
    projectId: 'posmission-dev',
    storageBucket: 'posmission-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPD6pmg0DzyENV0T9l5Tmuk4-ksI4aSzg',
    appId: '1:644074355722:ios:42f9c5e5470623b49fb3f3',
    messagingSenderId: '644074355722',
    projectId: 'posmission-dev',
    storageBucket: 'posmission-dev.appspot.com',
    iosBundleId: 'com.example.deelze',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPD6pmg0DzyENV0T9l5Tmuk4-ksI4aSzg',
    appId: '1:644074355722:ios:0dc753af8625c9039fb3f3',
    messagingSenderId: '644074355722',
    projectId: 'posmission-dev',
    storageBucket: 'posmission-dev.appspot.com',
    iosBundleId: 'com.example.deelze.RunnerTests',
  );
}
